# Generated by Django 2.2.10 on 2020-06-15 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('health', 'health'), ('general', 'general'), ('sales', 'sales'), ('project', 'project'), ('social', 'social'), ('retirement', 'retirement'), ('fulfillment', 'fulfillment'), ('other', 'other')], default=('general', 'general'), max_length=300)),
                ('priority', models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], default=('low', 'low'), max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
